version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - appnet
    command: --default-authentication-plugin=mysql_native_password
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 20

  backend:
    container_name: spring-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_FLYWAY_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      SPRING_FLYWAY_USER: ${DB_USER}
      SPRING_FLYWAY_PASSWORD: ${DB_PASSWORD}

      SECRET_KEY: ${SECRET_KEY}
      PLUGGY_ID: ${PLUGGY_ID}
      PLUGGY_SECRET: ${PLUGGY_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      # Observability
      OTEL_SERVICE_NAME: ${OTEL_SERVICE_NAME_BACKEND}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS}
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES_BACKEND}

    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_started
    networks:
      - appnet
    restart: always

  frontend:
    container_name: next-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://backend:8081

      # Observability
      OTEL_SERVICE_NAME: ${OTEL_SERVICE_NAME_FRONTEND}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS}
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES_FRONTEND}

    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    networks:
      - appnet
    restart: always

volumes:
  mysql_data:

networks:
  appnet:
    driver: bridge
