receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp/grafana:
    endpoint: https://otlp-gateway-prod-sa-east-1.grafana.net/otlp
    headers:
      Authorization: ${OTEL_EXPORTER_OTLP_HEADERS}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/grafana]
