receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp/grafana:
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
    headers:
      Authorization: ${OTEL_EXPORTER_OTLP_HEADERS}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/grafana]
