name: Backend SonarQube
on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze-backend:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Generate Gradle Wrapper
        working-directory: backend
        run: gradle wrapper --gradle-version 8.14

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('backend/**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build & Analyze Backend
        working-directory: backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          chmod +x gradlew
          ./gradlew build sonar --info
