name: Full CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build Backend
        working-directory: backend
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      
      - name: Deploy Docker Compose
        run: |
          cd $GITHUB_WORKSPACE
          docker compose -f docker-compose.yml up -d --remove-orphans
