name: Frontend SonarQube
on:
  workflow_run:
    workflows: ["Backend SonarQube"]
    types:
      - completed
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Run Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=thiagoarndtorg_finfam_frontend \
            -Dsonar.organization=thiagoarndtorg \
            -Dsonar.sources=.

